<?php

namespace shark\action;

use yii;
use yii\base\Action;
use Stripe;
use shark\models\forms\StripeForm;
use shark\models\Stripe as StripeModel;
use shark\models\StripeInfo;

class PayAction extends Action
{
    public $successCallback;

    public $config = [
        'callback_url' => '/successful',
        'setApiKey' => null,
    ];

    public function beforeRun()
    {
        if (isset($this->successCallback[0]) && is_array($this->successCallback[0])) {
            $this->config = array_merge($this->config, $this->successCallback[0]);
        }

        parent::beforeRun(); // TODO: Change the autogenerated stub
        return true;
    }

    /**
     * Runs the action.
     */
    public function run()
    {
        $status = StripeModel::STATUS_ERROR_APP;
        $stripeForm = new StripeForm();
        try {

            if ($stripeForm->load(Yii::$app->request->post()) && $stripeForm->validate()) {
                if (null == $this->config['setApiKey']) {
                    throw new \Exception('Token is failed');
                }

                Stripe\Stripe::setApiKey($this->config['setApiKey']);

                $charge = Stripe\Charge::create([
                    "amount" => $stripeForm->amount,
                    "currency" => $stripeForm->currency,
                    "description" => $stripeForm->description,
                    "source" => $stripeForm->source,
                ]);

                $status = ($charge && 'succeeded' == $charge->status)
                    ? StripeModel::STATUS_SUCCESS
                    : StripeModel::STATUS_ERROR_STRIPE_NOT_PAY;

                $stripeModel = new StripeModel();
                $stripeModel->setAttributes([
                    'amount' => $charge->amount,
                    'currency' => $charge->currency,
                    'status' => $charge->status,
                    'stripe_id' => $charge->id,
                    'type' => StripeModel::TYPE_PAY
                ]);
                $stripeModel->save();
            }

        } catch(Stripe\Error\Card $e) {
            $status = StripeModel::STATUS_ERROR_STRIPE;
        } catch(\Exception $e) {
            $status = StripeModel::STATUS_ERROR_APP;
        }

        return $this->controller->redirect([
                $this->config['callback_url'],
                'status' => $status,
                'id' => isset($stripeModel) ? $stripeModel->id : 0
            ]);
    }
}